// ============================================================
// MK Inbox Executive Command Center — Embedded Intelligence Data
// Source: pre-analyzed email intelligence from MK's Zoho inbox
// (mk@airev.ae, AIREV) — prepared 2026-07-02
// ============================================================

export const META = {
  title: "Meera's Command Centre",
  tagline: "Managing the CEO's Inbox",
  preparedFor: 'Meera AlDhaheri, Chief of Staff to MK',
  date: '2026-07-02',
  mailbox: 'mk@airev.ae',
  org: 'AIREV',
};

export const THREADS = [
  {
    id: 1,
    zoho: { messageId: '1782707570992154400', folderId: '6467483000000008014' },
    sender: 'Chris Li',
    email: 'kuixi.li@tcl.com',
    org: 'TCL RayNeo',
    role: 'Account Manager',
    subject: 'RayNeo X3 Pro purchase & Userdebug NDA',
    lastActivity: '2026-06-29',
    summary:
      'Chris sent stamped NDA back and SDK link (rayneo-en.gitbook.io/rayneo-devdoc); Sabiya forwarded NDA changes to Elena for review. AIREV owes NDA review/confirmation + purchase order progression for 3 units.',
    tier: 1,
    tierReason: 'Blocks Qualcomm NPU workload development; contractual document awaiting AIREV action.',
    sentiment: 'Positive / warm, formal',
    urgency: 8,
    risk: 6,
    bizValue: 8,
    relationship: 'Stable',
    owner: 'Sabiya / Elena, escalate to MK',
    action: 'Draft for MK approval — confirm NDA terms, stamp and return; progress PO for 3 units. Unblocks Qualcomm NPU workload development.',
    deadline: '2026-07-03',
    impact: 'Delays Qualcomm x AIREV hardware roadmap.',
    bucket: 'Draft for MK approval',
    category: 'Strategic Partners',
    draft:
      'Dear Chris,\n\nThank you for returning the stamped NDA and for sharing the RayNeo SDK documentation link. Our legal team has completed its review of the userdebug NDA terms, and we are pleased to confirm our acceptance. Please find the counter-stamped NDA attached.\n\nWe would also like to proceed with the purchase order for 3 units of the RayNeo X3 Pro. Kindly share the proforma invoice and expected delivery timeline so we can complete payment processing on our side.\n\nWe look forward to building on this collaboration, particularly around the Qualcomm NPU workload development.\n\nBest regards,\nMK\nAIREV — mk@airev.ae',
  },
  {
    id: 2,
    zoho: { messageId: '1782819435783141900', folderId: '6467483000000008014' },
    sender: 'Atul Sinha',
    email: 'atul.sinha@adports.ae',
    org: 'AD Ports Group',
    role: 'Manager, Data Strategy & Analytics',
    subject: 'AD Ports demo — Friday 11:00 AM',
    lastActivity: '2026-06-30',
    summary:
      'Atul proposed Friday 11:00 AM demo; Meera confirmed 2026-06-30 and asked for the invite. Enterprise client (maritime logistics).',
    tier: 2,
    tierReason: 'Confirmed enterprise demo this week; calendar logistics pending.',
    sentiment: 'Positive, warm / formal',
    urgency: 7,
    risk: 4,
    bizValue: 8,
    relationship: 'Healthy',
    owner: 'Meera',
    action: 'Ensure calendar invite received/sent for Friday 3 July 11:00; prep live demo of shareable mini-application feature.',
    deadline: '2026-07-02 EOD',
    impact: 'Missed demo slot with a flagship maritime-logistics enterprise prospect.',
    bucket: 'Send now',
    category: 'Government',
    draft: null,
  },
  {
    id: 3,
    zoho: { messageId: '1782463318810141900', folderId: '6467483000000008014' },
    sender: 'Fatma Al Yassi',
    email: 'fatma.alyassi@presight.ai',
    org: 'Presight / ADCCI',
    role: 'SME Upskilling Program',
    subject: 'Presight/ADCCI SME Upskilling meeting — Thu 2 July 11:00 AM',
    lastActivity: '2026-06-29',
    summary:
      'Fatma proposed Thursday 2 July 11:00 AM; awaiting AIREV confirmation. Meeting is TODAY. 500-SME government-linked program at stake.',
    tier: 1,
    tierReason: 'Meeting is TODAY 2026-07-02 and still unconfirmed — immediate action required.',
    sentiment: 'Positive, formal',
    urgency: 9,
    risk: 5,
    bizValue: 9,
    relationship: 'Healthy',
    owner: 'Meera',
    action: 'SEND NOW — confirm the 11:00 AM slot immediately and send the calendar invite.',
    deadline: '2026-07-02 09:00 GST',
    impact: '500-SME government-linked upskilling program at stake.',
    bucket: 'Send now',
    category: 'Government',
    draft:
      'Dear Fatma,\n\nThank you for proposing the meeting slot. We are pleased to confirm Thursday, 2 July at 11:00 AM for the SME Upskilling discussion.\n\nA calendar invite with the meeting details follows shortly. From our side, MK and the OnDemand program team will join.\n\nWe look forward to aligning on the next phase of the ADCCI SME upskilling initiative.\n\nWarm regards,\nMeera AlDhaheri\nChief of Staff, AIREV',
  },
  {
    id: 4,
    zoho: { messageId: '1782727445755141800', folderId: '6467483000000008014' },
    sender: 'Willy Liang',
    email: 'willy.liang@presight.ai',
    org: 'Presight',
    role: 'Senior Director',
    subject: 'Presight Ecommerce integration — working session + pending legal docs',
    lastActivity: '2026-07-01',
    summary:
      'Willy requests working session on AIREV OnDemand landing page hosting, Stripe payment gateway, Core42 infra. Reply debt: earlier chased pending legal documents pack (deadline was 3 June).',
    tier: 2,
    tierReason: 'Active senior-director request + overdue legal deliverable placing the relationship at risk.',
    sentiment: 'Neutral to concerned; urgent / formal',
    urgency: 8,
    risk: 7,
    bizValue: 9,
    relationship: 'At risk if legal docs stay pending',
    owner: 'MK + Legal',
    action: 'Escalate to MK — send legal T&Cs pack (overdue since 3 June) and confirm stakeholders for the working session.',
    deadline: 'ASAP — 2026-07-02',
    impact: 'Ecommerce integration stalls; senior-director trust erodes over overdue legal pack.',
    bucket: 'Escalate to MK',
    category: 'Legal / Contracts',
    draft:
      'Dear Willy,\n\nApologies for the delay on the legal documentation pack — please find attached the complete T&Cs pack covering the OnDemand landing page hosting and payment processing terms.\n\nOn the working session: we are aligned and would like to lock a slot this week. From our side MK, our infrastructure lead, and our payments engineer will cover landing page hosting, the Stripe payment gateway, and Core42 infrastructure integration. Could you share 2–3 windows that suit your team?\n\nThank you for your patience — we are committed to moving this forward quickly.\n\nBest regards,\nMK\nAIREV — mk@airev.ae',
  },
  {
    id: 5,
    sender: 'Waleed Qadamani',
    email: 'wqadaman@cisco.com',
    org: 'Cisco',
    role: 'Partner Engagement',
    subject: "Cisco 'Introducing AIREV OnDemand' session — Wed 8 July",
    lastActivity: '2026-07-02',
    summary:
      'Session rescheduled to Wednesday 8 July; Webex details shared. Team to confirm attendance and prep demo deck.',
    tier: 3,
    tierReason: 'Scheduled next week; needs confirmation and deck prep, not urgent today.',
    sentiment: 'Excited / positive',
    urgency: 5,
    risk: 3,
    bizValue: 7,
    relationship: 'Healthy',
    owner: 'MK / team',
    action: 'Confirm attendance, prep demo deck for 8 July Webex session.',
    deadline: '2026-07-07',
    impact: 'Weak first impression in a Cisco-wide introduction session.',
    bucket: 'Schedule meeting',
    category: 'Strategic Partners',
    draft: null,
  },
  {
    id: 6,
    zoho: { messageId: '1782720928770141900', folderId: '6467483000000008014' },
    sender: 'Mahra Al Alawi',
    email: 'mahra.89@hotmail.com',
    org: 'Private Investor',
    role: 'Investor',
    subject: 'AIREV investment — ADGM updates awaited',
    lastActivity: '2026-06-30',
    summary:
      "Awaiting ADGM updates; Elena last replied; Mahra says 'I look forward to hearing from you'. Previously chased for timelines — patience wearing thin. Board resolution + ROFR status owed.",
    tier: 2,
    tierReason: 'Investor relationship at risk; weekly progress update promised and now owed.',
    sentiment: 'Concerned / patient-but-frustrated',
    urgency: 7,
    risk: 8,
    bizValue: 8,
    relationship: 'Needs repair / at risk',
    owner: 'Youssef / Elena, escalate to MK',
    action: 'Send weekly progress update as promised; include board resolution + ROFR status.',
    deadline: '2026-07-02 EOD',
    impact: 'Investor confidence erodes; share issuance process stalls.',
    bucket: 'Draft for MK approval',
    category: 'Investors',
    draft:
      'Dear Mahra,\n\nThank you for your continued patience. As promised, here is this week\u2019s progress update on the investment process:\n\n1. Board resolution — drafted and circulated for signatures; we expect completion within 3 business days.\n2. ROFR waiver — notices issued to existing shareholders; the statutory response window closes this week.\n3. ADGM filing — our counsel has pre-validated the submission pack, so filing follows immediately once items 1–2 close.\n\nWe will continue sending you a written update every week until completion, and I am happy to jump on a call any time if useful.\n\nWith appreciation for your commitment to AIREV,\n\nBest regards,\nMK\nAIREV — mk@airev.ae',
  },
  {
    id: 7,
    zoho: { messageId: '1780757599457141900', folderId: '6467483000000008014' },
    sender: 'NEA Deal Desk',
    email: 'dealdesk@neaglobal.capital',
    org: 'NEA Venture Growth Equity',
    role: 'Deal Desk',
    subject: 'NEA Stage 1 business logic review',
    lastActivity: '2026-06-09',
    summary:
      'Stage 1 review with 4 detailed questions and a 2-business-day deadline; Youssef sent answers 2026-06-09; no NEA response for ~23 days. NOTE: domain neaglobal.capital differs from official NEA — verify legitimacy.',
    tier: 3,
    tierReason: 'Quiet thread (~23 days); potential opportunity but legitimacy unverified.',
    sentiment: 'Neutral / formal',
    urgency: 5,
    risk: 6,
    bizValue: 6,
    relationship: 'Unclear — legitimacy check pending',
    owner: 'Youssef, flag to MK',
    action: 'Send follow-up checking evaluation status. FLAG: verify legitimacy of neaglobal.capital domain vs official NEA before sharing anything further.',
    deadline: '2026-07-03',
    impact: 'Either a stalled funding lead — or continued exposure to a possible impersonation attempt.',
    bucket: 'Escalate to MK',
    category: 'Investors',
    draft:
      'Dear NEA Deal Desk team,\n\nI hope this finds you well. On 9 June we submitted our responses to the four Stage 1 business logic questions within the requested two-business-day window.\n\nCould you kindly confirm receipt and share an update on the evaluation status and expected next steps in the process?\n\nFor good order, could you also confirm the engagement through your official corporate channels? We are glad to continue the conversation via a verified point of contact.\n\nBest regards,\nYoussef\nAIREV — on behalf of MK',
  },
  {
    id: 8,
    sender: 'Elena Rabi',
    email: 'elena.rabi@lockton.com',
    org: 'Lockton (MENA)',
    role: 'SME Agentic AI Pilot contact',
    subject: 'Lockton SME Agentic AI Pilot — Thursday office visit',
    lastActivity: '2026-06-29',
    summary:
      'Meera followed up proposing Thursday office visit; no reply from Lockton. Chronic non-responsiveness pattern. Government-linked (Abu Dhabi Chamber / G42 / Presight).',
    tier: 3,
    tierReason: 'Quiet thread; ball in their court, but chronic silence risks pilot slippage.',
    sentiment: 'Passive / at risk',
    urgency: 6,
    risk: 7,
    bizValue: 7,
    relationship: 'At risk — repeated non-responsiveness',
    owner: 'Meera',
    action: 'Final follow-up; if silent again, flag to ADCCI focal points.',
    deadline: '2026-07-03',
    impact: 'SME Agentic AI pilot loses momentum inside a government-linked program.',
    bucket: 'Send now',
    category: 'Enterprise Clients',
    draft: null,
  },
  {
    id: 9,
    zoho: { messageId: '1781111246501141900', folderId: '6467483000000008014' },
    sender: 'Rick Bunker / Darrell Starnes',
    email: 'rbunker@inveniam.io',
    org: 'Inveniam',
    role: 'CTO / Engineering',
    subject: 'TraceChain architecture change — content off immutable core',
    lastActivity: '2026-06-22',
    summary:
      "Content moves off immutable core; REST API first, MCP later; new TraceChain version to DevOps early next week. Follow-on 'Trace Chain deployment' thread from Patrick O'Meara 2026-06-22.",
    tier: 3,
    tierReason: 'Technical partner update requiring internal engineering review, not exec action.',
    sentiment: 'Neutral / technical',
    urgency: 4,
    risk: 4,
    bizValue: 6,
    relationship: 'Stable',
    owner: 'Engineering (delegate)',
    action: 'Delegate internally — engineering to review repo design doc and align integration plan.',
    deadline: '2026-07-08',
    impact: 'Integration drift with a strategic tokenization partner.',
    bucket: 'Delegate internally',
    category: 'Product / Technical',
    draft: null,
  },
  {
    id: 10,
    sender: 'Sejoe Thomas / K. Tahboub',
    email: 'qualcomm@qualcomm.com',
    org: 'Qualcomm',
    role: 'Partnership team',
    subject: 'AIREV x Qualcomm — Onboarding OnDemand on Appliance Server',
    lastActivity: '2026-06-22',
    summary:
      "Signing ceremony completed 22 June; 'Onboarding OnDemand on Appliance Server' meeting invites accepted (Sejoe Thomas, K. Tahboub).",
    tier: 4,
    tierReason: 'Informational — milestone completed, meetings accepted; only tracking needed.',
    sentiment: 'Excited / positive — relationship improving',
    urgency: 3,
    risk: 2,
    bizValue: 9,
    relationship: 'Improving',
    owner: 'MK',
    action: 'Archive / track. Ensure appliance-server onboarding sessions are attended.',
    deadline: '—',
    impact: 'None immediate; keep the momentum visible internally.',
    bucket: 'Archive',
    category: 'Strategic Partners',
    draft: null,
  },
  {
    id: 11,
    sender: 'Amin Kamhie',
    email: 'amin.kamhie@alphadata.ae',
    org: 'Alpha Data',
    role: 'Bid team',
    subject: 'RFX-DPA-250090 — ICIP Project: DPA Centralized Platform & Dashboard Enhancement',
    lastActivity: '2026-06-25',
    summary:
      'Amin forwarded RFX 2026-06-14; William replied 2026-06-25. Enterprise/government bid — status unclear since.',
    tier: 3,
    tierReason: 'Live government bid with unclear internal status — needs confirmation, not escalation.',
    sentiment: 'Neutral / formal',
    urgency: 6,
    risk: 5,
    bizValue: 7,
    relationship: 'Stable',
    owner: 'William',
    action: 'Confirm bid status with William; verify submission timeline for RFX-DPA-250090.',
    deadline: '2026-07-04',
    impact: 'Missed government-bid deadline for the DPA centralized platform project.',
    bucket: 'Delegate internally',
    category: 'Enterprise Clients',
    draft: null,
  },
  {
    id: 12,
    sender: 'Julia B.',
    email: 'julia@wowpayments.us',
    org: 'WOW Payments',
    role: 'Sales',
    subject: 'US payment processing offer',
    lastActivity: '2026-06-16',
    summary: 'Unsolicited US payment processing offer; last touch 2026-06-16.',
    tier: 5,
    tierReason: 'Low-value vendor outreach; no strategic urgency.',
    sentiment: 'Neutral / salesy',
    urgency: 2,
    risk: 1,
    bizValue: 3,
    relationship: 'N/A',
    owner: 'Finance',
    action: 'Archive or delegate to finance for a standard evaluation.',
    deadline: '—',
    impact: 'None.',
    bucket: 'Delegate internally',
    category: 'Finance / Payments',
    draft: null,
  },
  {
    id: 13,
    sender: 'AXM Congress Updates',
    email: 'updates@mail.axmcongress.com',
    org: 'AXM Congress 2026',
    role: 'Event organizer',
    subject: 'AXM Congress 2026 (Geneva, 8 July) — last call for participation',
    lastActivity: '2026-07-02',
    summary: 'Last call for participation in AXM Congress 2026, Geneva, 8 July.',
    tier: 4,
    tierReason: 'Media/PR opportunity; only relevant if MK wants presence.',
    sentiment: 'Neutral / promotional',
    urgency: 3,
    risk: 2,
    bizValue: 4,
    relationship: 'N/A',
    owner: 'MK (decision only)',
    action: 'Archive unless MK wants presence — decision needed before 8 July.',
    deadline: '2026-07-04',
    impact: 'Missed optional PR slot; low impact.',
    bucket: 'Archive',
    category: 'Media / PR',
    draft: null,
  },
  {
    id: 14,
    zoho: { messageId: '1781351668366141900', folderId: '6467483000000008014' },
    sender: 'On-Demand Automation',
    email: 'info@on-demand.io',
    org: 'AIREV (internal)',
    role: 'Automation system',
    subject: 'Automation failure report — Qatar workflow',
    lastActivity: '2026-06-27',
    summary: 'Qatar workflow execution: 0 verified sends, gates breached. Internal ops issue.',
    tier: 4,
    tierReason: 'Internal ops fix; no external counterparty waiting.',
    sentiment: 'Neutral / system alert',
    urgency: 4,
    risk: 3,
    bizValue: 4,
    relationship: 'Internal',
    owner: 'Ops / engineering',
    action: 'Delegate — fix workflow targeting and re-run verification gates.',
    deadline: '2026-07-04',
    impact: 'Qatar outreach automation remains broken.',
    bucket: 'Delegate internally',
    category: 'Product / Technical',
    draft: null,
  },
  {
    id: 15,
    sender: 'On-Demand Research',
    email: 'info@on-demand.io',
    org: 'AIREV (internal)',
    role: 'Research automation',
    subject: 'NAFFCO research brief delivered (PDF)',
    lastActivity: '2026-06-25',
    summary:
      'Research brief on NAFFCO delivered. Opportunity: approach Group MD Ali Khalid Al Khatib with OnDemand Enterprise proposal.',
    tier: 4,
    tierReason: 'Informational with an embedded opportunity; no counterparty waiting.',
    sentiment: 'Neutral / informational',
    urgency: 3,
    risk: 2,
    bizValue: 6,
    relationship: 'N/A (prospect)',
    owner: 'BD team',
    action: 'Archive brief; open BD play — approach Group MD Ali Khalid Al Khatib with OnDemand Enterprise proposal.',
    deadline: '—',
    impact: 'Unworked enterprise lead.',
    bucket: 'Archive',
    category: 'Enterprise Clients',
    draft: null,
  },
  {
    id: 16,
    zoho: { messageId: '1780729226917141900', folderId: '6467483000000008014' },
    sender: 'Newsletters (The GPU #109, Inveniam marketing, stock report)',
    email: 'various',
    org: 'Various',
    role: 'Newsletters',
    subject: 'The GPU #109 · Inveniam marketing · stock analysis report',
    lastActivity: '2026-06-26',
    summary: 'Routine newsletters and marketing digests.',
    tier: 5,
    tierReason: 'Zero action value.',
    sentiment: 'N/A',
    urgency: 1,
    risk: 1,
    bizValue: 1,
    relationship: 'N/A',
    owner: '—',
    action: 'Archive.',
    deadline: '—',
    impact: 'None.',
    bucket: 'Archive',
    category: 'Media / PR',
    draft: null,
  },
];

export const TIER_INFO = {
  1: { label: 'Tier 1 — Act Today', color: '#0B3D2E', text: '#ffffff', ink: '#0B3D2E', desc: 'Immediate action required today' },
  2: { label: 'Tier 2 — This Week, High Stakes', color: '#135C43', text: '#ffffff', ink: '#135C43', desc: 'High-stakes items needing action this week' },
  3: { label: 'Tier 3 — Monitor & Nudge', color: '#1B7355', text: '#ffffff', ink: '#17694F', desc: 'Follow-ups, quiet threads, scheduled items' },
  4: { label: 'Tier 4 — Informational / Delegate', color: '#A9D2C1', text: '#0B3D2E', ink: '#1B7355', desc: 'Tracking, internal fixes, FYI items' },
  5: { label: 'Tier 5 — Archive', color: '#DFEEE7', text: '#0B3D2E', ink: '#52675C', desc: 'No action value — archive' },
};

// tier counts (validated): T1:2 (TCL, Presight-Fatma) T2:3 (ADPorts, Willy, Mahra)
// T3:5 (Cisco, NEA, Lockton, Inveniam, AlphaData) T4:4 (Qualcomm, AXM, Qatar wf, NAFFCO) T5:2 (WOW, Newsletters)
export const TIER_COUNTS = { 1: 2, 2: 3, 3: 5, 4: 4, 5: 2 };

export const QUIET_THREADS = [
  {
    id: 'q1',
    threadId: 7,
    counterparty: 'NEA Venture Growth Equity (dealdesk@neaglobal.capital)',
    lastMessage: '2026-06-09',
    daysQuiet: 23,
    lastResponder: 'Youssef (AIREV) — sent Stage 1 answers',
    topic: 'Stage 1 business logic review — 4 questions answered within their 2-day deadline',
    whereLeft: 'AIREV answered on time; NEA has gone silent for ~23 days.',
    owesReply: 'They owe us',
    risk: 'Medium-High',
    riskColor: '#B54708',
    followUp:
      'Dear NEA Deal Desk — following our Stage 1 submission on 9 June, could you confirm receipt and share the evaluation status and expected next steps? We would also appreciate confirmation via your official corporate channels. — Youssef, AIREV',
    note: 'Verify legitimacy: neaglobal.capital differs from official NEA domain — flag to MK before deeper engagement.',
  },
  {
    id: 'q2',
    threadId: 8,
    counterparty: 'Elena Rabi — Lockton (MENA)',
    lastMessage: '2026-06-29',
    daysQuiet: 3,
    lastResponder: 'Meera (AIREV) — proposed Thursday office visit',
    topic: 'SME Agentic AI Pilot — office visit proposal',
    whereLeft: 'AIREV proposed Thursday visit; Lockton silent again (chronic pattern).',
    owesReply: 'They owe us (chronic)',
    risk: 'High (chronic non-responsiveness)',
    riskColor: '#B42318',
    followUp:
      'Hi Elena — circling back on the Thursday office visit for the SME Agentic AI pilot. If this week no longer works, happy to propose alternatives. If we don\u2019t hear back by Friday we\u2019ll check in with the ADCCI focal points to keep the pilot timeline on track. — Meera',
    note: 'Final nudge, then escalate to ADCCI focal points.',
  },
  {
    id: 'q3',
    threadId: 6,
    counterparty: 'Mahra Al Alawi (mahra.89@hotmail.com)',
    lastMessage: '2026-06-30',
    daysQuiet: 2,
    lastResponder: 'Elena (AIREV) — but weekly update now due',
    topic: 'AIREV investment — ADGM process, board resolution, ROFR',
    whereLeft: "Mahra waiting: 'I look forward to hearing from you.' Weekly update promised and now owed.",
    owesReply: 'We owe them',
    risk: 'High (relationship repair needed)',
    riskColor: '#B42318',
    followUp:
      'Dear Mahra — as promised, this week\u2019s update: board resolution circulating for signature, ROFR notices issued, ADGM pack pre-validated for immediate filing once both close. Full written update every week until completion. — MK',
    note: 'Board/shareholder category — highest relationship sensitivity.',
  },
  {
    id: 'q4',
    threadId: 11,
    counterparty: 'Amin Kamhie — Alpha Data',
    lastMessage: '2026-06-25',
    daysQuiet: 7,
    lastResponder: 'William (AIREV)',
    topic: 'RFX-DPA-250090 — ICIP DPA Centralized Platform & Dashboard Enhancement bid',
    whereLeft: 'William replied 25 June; no confirmation on bid status since.',
    owesReply: 'Internal status check',
    risk: 'Medium',
    riskColor: '#7A5200',
    followUp:
      'Hi William — quick status check on RFX-DPA-250090 (ICIP DPA platform): are we submitting, and what\u2019s the deadline? Flag anything you need from MK\u2019s side today. — Meera',
    note: 'Government bid — deadline risk if left unconfirmed.',
  },
];

export const REPLY_DEBT = [
  {
    id: 'd1',
    threadId: 4,
    item: 'Presight legal T&Cs / documents pack',
    counterparty: 'Willy Liang (Presight, Senior Director)',
    severity: 'HIGH — OVERDUE',
    sevColor: '#B42318',
    dueDate: '2026-06-03',
    daysElapsed: 29,
    detail: 'Legal docs pack deadline was 3 June — 29 days overdue. Willy has chased politely but firmly. Relationship at risk.',
    action: 'Send pack today with cover note + working-session stakeholder confirmation.',
  },
  {
    id: 'd2',
    threadId: 6,
    item: 'Weekly investor progress update',
    counterparty: 'Mahra Al Alawi (Investor)',
    severity: 'HIGH',
    sevColor: '#B54708',
    dueDate: '2026-07-02',
    daysElapsed: 2,
    detail: 'Weekly update promised; last AIREV reply 2026-06-30 did not include the committed board-resolution/ROFR status.',
    action: 'Send written weekly update (board resolution + ROFR + ADGM) by EOD.',
  },
  {
    id: 'd3',
    threadId: 3,
    item: 'Meeting confirmation — Thu 2 July 11:00',
    counterparty: 'Fatma Al Yassi (Presight/ADCCI)',
    severity: 'CRITICAL — TODAY',
    sevColor: '#8E1508',
    dueDate: '2026-07-02 09:00',
    daysElapsed: 3,
    detail: 'Slot proposed 2026-06-29; meeting is today at 11:00 and AIREV has not confirmed.',
    action: 'Confirm 11:00 AM now and send invite.',
  },
  {
    id: 'd4',
    threadId: 1,
    item: 'TCL NDA review, stamp & return',
    counterparty: 'Chris Li (TCL RayNeo)',
    severity: 'MEDIUM-HIGH',
    sevColor: '#7A5200',
    dueDate: '2026-07-03',
    daysElapsed: 3,
    detail: 'Chris returned stamped NDA 2026-06-29; AIREV owes review confirmation + counter-stamp + PO progression (3 units).',
    action: 'Elena finalizes review; MK approves; return stamped NDA + PO.',
  },
];

export const SENTIMENT_RADAR = [
  { stakeholder: 'TCL RayNeo', sentiment: 8, tone: 8, health: 8, concern: 'None visible — steady, formal cadence. Keep momentum on NDA to avoid cooling.' },
  { stakeholder: 'AD Ports', sentiment: 8, tone: 8, health: 8, concern: 'None — warm and confirmed. Only logistics risk (invite not circulating).' },
  { stakeholder: 'Presight', sentiment: 5, tone: 5, health: 5, concern: "Willy's polite-but-firm deadline pressure on the legal pack; goodwill from Fatma's track offsets — for now." },
  { stakeholder: 'Lockton', sentiment: 4, tone: 5, health: 3, concern: 'Chronic non-responsiveness; pilot enthusiasm may have faded internally.' },
  { stakeholder: 'Mahra (Investor)', sentiment: 4, tone: 6, health: 4, concern: "Patience wearing thin — 'I look forward to hearing from you' is a soft final warning." },
  { stakeholder: 'NEA', sentiment: 5, tone: 6, health: 4, concern: 'Possible legitimacy issue — domain mismatch with official NEA. Treat silence as a caution signal.' },
  { stakeholder: 'Qualcomm', sentiment: 9, tone: 9, health: 9, concern: 'None — post-signing high. Convert energy into appliance-server delivery.' },
  { stakeholder: 'Inveniam', sentiment: 6, tone: 6, health: 7, concern: 'Purely technical traffic; ensure engineering responds to architecture change to avoid drift.' },
];

export const OPPORTUNITY_MAP = [
  {
    category: 'Investors',
    color: '#0B3D2E',
    entities: ['Mahra Al Alawi', 'NEA Venture Growth'],
    nextSteps: 'Restore Mahra cadence with weekly written updates; verify NEA legitimacy before deeper engagement, then follow up on Stage 1.',
  },
  {
    category: 'Government',
    color: '#135C43',
    entities: ['ADCCI', 'AD Ports', 'Presight / G42'],
    nextSteps: 'Confirm today\u2019s ADCCI SME meeting; deliver Friday AD Ports demo; use the 500-SME program as the wedge into the wider G42 ecosystem.',
  },
  {
    category: 'Enterprise Clients',
    color: '#17694F',
    entities: ['Lockton', 'NAFFCO', 'Alpha Data'],
    nextSteps: 'Final Lockton nudge then ADCCI escalation; open NAFFCO play via Group MD Ali Khalid Al Khatib; confirm Alpha Data RFX bid status.',
  },
  {
    category: 'Strategic Partners',
    color: '#1B7355',
    entities: ['Qualcomm', 'TCL RayNeo', 'Cisco', 'Inveniam'],
    nextSteps: 'Ride Qualcomm post-signing momentum; close TCL NDA to unblock NPU work; prep Cisco 8-July session; keep Inveniam integration aligned.',
  },
  {
    category: 'Legal / Contracts',
    color: '#0E6245',
    entities: ['TCL NDA', 'Presight T&Cs pack'],
    nextSteps: 'Two live legal items, both blocking business: return TCL NDA by 3 July; send overdue Presight T&Cs pack TODAY.',
  },
  {
    category: 'Finance / Payments',
    color: '#104A37',
    entities: ['WOW Payments', 'Stripe integration'],
    nextSteps: 'Delegate WOW evaluation to finance; fold Stripe gateway decisions into the Presight ecommerce working session.',
  },
  {
    category: 'Product / Technical',
    color: '#052A1E',
    entities: ['TraceChain', 'Appliance Server', 'Qatar workflow'],
    nextSteps: 'Engineering reviews TraceChain design doc; staff Qualcomm appliance-server onboarding; fix Qatar workflow targeting.',
  },
  {
    category: 'Media / PR',
    color: '#135C43',
    entities: ['AXM Congress 2026 (Geneva, 8 July)'],
    nextSteps: 'MK decision by 4 July: attend or archive. Conflicts with Cisco session on the same day — default to archive.',
  },
  {
    category: 'Board / Shareholder',
    color: '#0B3D2E',
    entities: ['Mahra share issuance (board resolution, ROFR, ADGM)'],
    nextSteps: 'Complete board resolution signatures, close ROFR window, file with ADGM — then confirm allotment to Mahra.',
  },
];

export const ACTION_BUCKETS = [
  {
    bucket: 'Send now',
    color: '#052A1E',
    icon: 'zap',
    items: [
      'Confirm Presight/ADCCI 11:00 AM meeting (TODAY — send by 09:00)',
      'Verify/send AD Ports Friday 11:00 demo calendar invite',
      'Final Lockton follow-up on Thursday office visit',
    ],
  },
  {
    bucket: 'Draft for MK approval',
    color: '#0B3D2E',
    icon: 'pen-line',
    items: [
      'TCL NDA confirmation + counter-stamp + PO progression',
      'Mahra investor weekly update (board resolution + ROFR + ADGM)',
      'Presight legal pack cover note to Willy Liang',
    ],
  },
  {
    bucket: 'Schedule meeting',
    color: '#104A37',
    icon: 'calendar',
    items: [
      'Presight ecommerce working session (hosting, Stripe, Core42)',
      'Cisco 8 July session prep + attendance confirmation',
    ],
  },
  {
    bucket: 'Escalate to MK',
    color: '#135C43',
    icon: 'alert-triangle',
    items: [
      'Presight legal docs pack — 29 days overdue (relationship risk)',
      'NEA legitimacy check — domain mismatch (neaglobal.capital vs official NEA)',
    ],
  },
  {
    bucket: 'Delegate internally',
    color: '#17694F',
    icon: 'users',
    items: [
      'TraceChain architecture review — engineering',
      'Qatar workflow fix (0 verified sends) — ops',
      'WOW Payments evaluation — finance',
      'Alpha Data RFX status — William',
    ],
  },
  {
    bucket: 'Archive',
    color: '#1B7355',
    icon: 'archive',
    items: [
      'Newsletters (The GPU #109, Inveniam marketing, stock report)',
      'AXM Congress (unless MK wants Geneva presence)',
      'NAFFCO brief (after logging the BD opportunity)',
      'Qualcomm signing-ceremony thread (milestone complete)',
    ],
  },
];

export const MACHINE_SUMMARY = {
  tier_counts: { tier1: 2, tier2: 3, tier3: 5, tier4: 4, tier5: 2 },
  reply_debt_count: 4,
  quiet_thread_count: 4,
  top_5_urgent_actions: [
    { rank: 1, action: 'Confirm Presight ADCCI meeting Thu 2 July 11:00', deadline: '2026-07-02T09:00:00+04:00' },
    { rank: 2, action: 'Return stamped TCL NDA', deadline: '2026-07-03' },
    { rank: 3, action: 'Send Presight legal T&Cs pack to Willy Liang (overdue)', deadline: '2026-07-02 ASAP' },
    { rank: 4, action: 'Send Mahra Al Alawi investor progress update', deadline: '2026-07-02 EOD' },
    { rank: 5, action: 'Confirm AD Ports Friday 3 July 11:00 demo invite', deadline: '2026-07-02 EOD' },
  ],
};
